# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-05-16 · Project: ZINC-FUSION-V16

from __future__ import annotations

import re
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


def read_text(rel_path: str) -> str:
    return (REPO_ROOT / rel_path).read_text(encoding="utf-8", errors="replace")


class SpecRequirementsFunctionalTest(unittest.TestCase):
    def test_req001_all_ingest_writers_include_run_id_and_canonical_status(self) -> None:
        """[Req: inferred — REQ-001] All ingest writers use unified run-id lifecycle contract."""
        ddl = read_text("supabase/migrations/202603180009_ops_vegas.sql")
        legacy_ingest = read_text("supabase/migrations/20260414001_ingest_zl_intraday.sql")
        trusted_ingest = read_text("supabase/migrations/202605080003_supabase_trusted_site_fill_hourly.sql")
        ts_writer = read_text("lib/server/ingest-run.ts")

        self.assertRegex(ddl, r"run_id\s+UUID\s+PRIMARY\s+KEY")
        self.assertIn("run_id", trusted_ingest)
        self.assertIn("run_id", ts_writer)
        # Desired-state assertion: legacy SQL writer should also include run_id inserts.
        self.assertRegex(legacy_ingest, r"INSERT INTO ops\.ingest_run \(run_id,")

    def test_req002_no_runtime_or_gate_dependency_on_api_cron_path(self) -> None:
        """[Req: inferred — REQ-002] Cron route shape is not required by middleware or verification gates."""
        proxy = read_text("lib/supabase/proxy.ts")
        gate3 = read_text("scripts/verify/gate3.sh")
        agents = read_text("AGENTS.md")

        self.assertIn("No Inngest. No Vercel Cron.", agents)
        self.assertNotIn("/api/cron/", proxy)
        self.assertNotRegex(gate3, r"rg\s+app/api/cron")

    def test_req003_intraday_route_contract_matches_implemented_fallback(self) -> None:
        """[Req: inferred — REQ-003] Intraday fallback comments match executable query behavior."""
        route = read_text("app/api/zl/intraday/route.ts")
        self.assertIn("fallback", route.lower())
        self.assertIn("mkt.price_15m", route)
        # Desired-state assertion: explicit query path to 1m source exists when fallback is documented.
        self.assertIn("mkt.price_1m", route)

    def test_req004_contract_and_gate_align_on_warning_semantics(self) -> None:
        """[Req: inferred — REQ-004] Optional warning semantics are consistent across contract and parity gates."""
        api_contract = read_text("lib/contracts/api.ts")
        gate6 = read_text("scripts/verify/gate6.sh")

        self.assertRegex(api_contract, r"warning\?:\s*string")
        # Desired-state assertion: gate should not require warning on every success payload.
        self.assertNotRegex(gate6, r'\.warning\s*\|\|\s*empty')

    def test_req005_risk_factor_payload_exposes_mixed_vintage_metadata(self) -> None:
        """[Req: inferred — REQ-005] Mixed-vintage freshness metadata is emitted and rendered."""
        api = read_text("app/api/dashboard/risk-factors/route.ts")
        ui = read_text("components/dashboard/MarketRiskFactors.tsx")

        for field in ["as_of_date", "as_of_date_min", "as_of_date_max", "mixed_vintage"]:
            self.assertIn(field, api)
        self.assertRegex(ui, r"mixed[-_ ]vintage|as_of_date_min|as_of_date_max")

    def test_req006_normalize_horizon_logic_is_identical_across_three_routes(self) -> None:
        """[Req: inferred — REQ-006] Horizon normalization logic remains equivalent across forecast surfaces."""
        files = {
            "forecast": "app/api/zl/forecast/route.ts",
            "target_zones": "app/api/zl/target-zones/route.ts",
            "forecast_targets": "app/api/zl/forecast-targets/route.ts",
        }

        extracted: dict[str, list[str]] = {}
        pattern = re.compile(
            r"const AG_HORIZON_DAYS|const LEGACY_HORIZON_MAP|function normalizeHorizon|if \(modelVersion === \"legacy\"\)|return AG_HORIZON_DAYS\.has",
        )
        for key, rel in files.items():
            lines = []
            for line in read_text(rel).splitlines():
                if pattern.search(line):
                    lines.append(line.strip())
            extracted[key] = lines

        self.assertEqual(extracted["forecast"], extracted["target_zones"])
        self.assertEqual(extracted["forecast"], extracted["forecast_targets"])


class FitnessScenarioFunctionalTest(unittest.TestCase):
    def test_scenario_snapshot_source_whitelist_is_explicit_and_auditable(self) -> None:
        """[Req: inferred — REQ-004] Snapshot source whitelist is explicit and finite."""
        text = read_text("lib/server/ai-snapshot.ts")
        values = re.findall(r'"(strategy|sentiment|legislation|vegas-intel)"', text)
        self.assertEqual(sorted(set(values)), ["legislation", "sentiment", "strategy", "vegas-intel"])

    def test_scenario_pipeline_order_and_scaffold_modules_are_visible(self) -> None:
        """[Req: inferred — REQ-001] Scaffold phases remain explicit in pipeline orchestration."""
        pipeline = read_text("python/fusion/pipeline.py")
        forecast = read_text("python/fusion/generate_forward_forecasts.py")
        garch = read_text("python/fusion/run_garch.py")
        monte = read_text("python/fusion/run_monte_carlo.py")
        zones = read_text("python/fusion/generate_target_zones.py")

        for phase in ["forecast", "garch", "monte-carlo", "target-zones"]:
            self.assertIn(phase, pipeline)

        self.assertIn("status", forecast)
        self.assertIn("scaffold", forecast)
        self.assertIn("scaffold", garch)
        self.assertIn("scaffold", monte)
        self.assertIn("scaffold", zones)

    def test_scenario_freshness_ui_does_not_drop_mixed_vintage_context(self) -> None:
        """[Req: inferred — REQ-005] UI keeps mixed-vintage context near freshness labels."""
        ui = read_text("components/dashboard/MarketRiskFactors.tsx")
        self.assertRegex(ui, r"as_of_date|max|min|mixed")


class BoundaryAndEdgeCasesFunctionalTest(unittest.TestCase):
    def test_boundary_horizon_allowlist_contains_only_canonical_values(self) -> None:
        """[Req: inferred — REQ-006] Canonical horizon allowlist remains [30, 90, 180]."""
        for rel in [
            "app/api/zl/forecast/route.ts",
            "app/api/zl/target-zones/route.ts",
            "app/api/zl/forecast-targets/route.ts",
        ]:
            text = read_text(rel)
            self.assertRegex(text, r"new Set\(\[30,\s*90,\s*180\]\)")

    def test_boundary_legacy_horizon_map_is_preserved(self) -> None:
        """[Req: inferred — REQ-006] Legacy map preserves 7→30, 14→90, 30→180."""
        text = read_text("app/api/zl/forecast/route.ts")
        self.assertIn("7: 30", text)
        self.assertIn("14: 90", text)
        self.assertIn("30: 180", text)

    def test_boundary_proxy_helper_still_handles_nextjs_internal_paths(self) -> None:
        """[Req: inferred — REQ-002] Middleware keeps internal Next.js exceptions while avoiding cron-route dependency."""
        proxy = read_text("lib/supabase/proxy.ts")
        self.assertRegex(proxy, r"/_next|favicon|static")


if __name__ == "__main__":
    unittest.main()
