#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-05-16 · Project: ZINC-FUSION-V16

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

status=0

compare_artifact() {
  local expected_file="$1"
  local extractor="$2"
  local tmp
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' RETURN

  eval "$extractor" > "$tmp"
  if ! diff -u "$expected_file" "$tmp"; then
    echo "FAIL: artifact mismatch -> $expected_file"
    status=1
  else
    echo "PASS: $expected_file"
  fi

  rm -f "$tmp"
  trap - RETURN
}

compare_artifact \
  "quality/mechanical/forecast_normalize_horizon_cases.txt" \
  "awk '/const AG_HORIZON_DAYS/ {in_block=1} in_block && /\\[30, 90, 180\\]|7: 30|14: 90|30: 180/ {line=\$0; gsub(/^[[:space:]]+/, \"\", line); print line} in_block && /};/ {exit}' app/api/zl/forecast/route.ts"

compare_artifact \
  "quality/mechanical/target_zones_normalize_horizon_cases.txt" \
  "awk '/const AG_HORIZON_DAYS/ {in_block=1} in_block && /\\[30, 90, 180\\]|7: 30|14: 90|30: 180/ {line=\$0; gsub(/^[[:space:]]+/, \"\", line); print line} in_block && /};/ {exit}' app/api/zl/target-zones/route.ts"

compare_artifact \
  "quality/mechanical/forecast_targets_normalize_horizon_cases.txt" \
  "awk '/const AG_HORIZON_DAYS/ {in_block=1} in_block && /\\[30, 90, 180\\]|7: 30|14: 90|30: 180/ {line=\$0; gsub(/^[[:space:]]+/, \"\", line); print line} in_block && /};/ {exit}' app/api/zl/forecast-targets/route.ts"

compare_artifact \
  "quality/mechanical/trusted_snapshot_sources_cases.txt" \
  "awk '/TRUSTED_SNAPSHOT_SOURCES/ {in_block=1; next} in_block && /\\]\\);/ {exit} in_block && /\"/ {line=\$0; gsub(/[\",]/, \"\", line); gsub(/^[[:space:]]+/, \"\", line); print line}' lib/server/ai-snapshot.ts"

compare_artifact \
  "quality/mechanical/ingest_status_cases.txt" \
  "(rg --no-filename -o '\"(RUNNING|SUCCESS|FAILED)\"' lib/server/ingest-run.ts | tr -d '\"' | sort -u; rg --no-filename -o \"'(running|ok|failed)'\" supabase/migrations/20260414001_ingest_zl_intraday.sql supabase/migrations/202605080003_supabase_trusted_site_fill_hourly.sql | tr -d \"'\" | tr '[:lower:]' '[:upper:]' | sort -u) | sort -u"

if [[ "$status" -ne 0 ]]; then
  echo "MECHANICAL VERIFY: FAIL"
  exit "$status"
fi

echo "MECHANICAL VERIFY: PASS"
