# Generated by Quality Playbook v1.5.7 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-05-16 · Project: ZINC-FUSION-V16

from __future__ import annotations

import re
import unittest
from pathlib import Path
from unittest.mock import patch

from fusion import pipeline

ROOT = Path(__file__).resolve().parents[1]


def read_text(relative_path: str) -> str:
    return (ROOT / relative_path).read_text(encoding="utf-8")


class SpecRequirementTests(unittest.TestCase):
    def test_req_001_intraday_route_contains_executable_1m_fallback(self) -> None:
        """[Req: code-derived — REQ-001] intraday route must execute 15m->1m fallback."""
        source = read_text("app/api/zl/intraday/route.ts")
        self.assertIn("Try 15-minute bars first, fall back to 1-minute", source)
        self.assertIn('.from("price_15m")', source)
        self.assertIn(
            '.from("price_1m")',
            source,
            "REQ-001 violation: 1-minute fallback query path is not implemented.",
        )

    def test_req_002_forecast_target_routes_share_api_envelope_contract(self) -> None:
        """[Req: code-derived — REQ-002] equivalent target routes should share envelope semantics."""
        target_zones = read_text("app/api/zl/target-zones/route.ts")
        forecast_targets = read_text("app/api/zl/forecast-targets/route.ts")
        self.assertIn("ok: true", target_zones)
        self.assertIn("data:", target_zones)
        self.assertIn("asOf:", target_zones)
        self.assertIn(
            "ok: true",
            forecast_targets,
            "REQ-002 violation: forecast-targets route does not emit canonical envelope keys.",
        )
        self.assertIn("data:", forecast_targets)
        self.assertIn("asOf:", forecast_targets)

    def test_req_003_ingest_status_vocab_is_canonical_across_writers(self) -> None:
        """[Req: code-derived — REQ-003] all ingest writers should share one status vocabulary."""
        helper = read_text("lib/server/ingest-run.ts")
        sql_intraday = read_text("supabase/migrations/20260414001_ingest_zl_intraday.sql")
        sql_fill = read_text("supabase/migrations/202605080003_supabase_trusted_site_fill_hourly.sql")

        helper_statuses = set(re.findall(r'status:\s*"([A-Z_]+)"', helper))
        sql_statuses = set(re.findall(r"status\s*:=\s*'([a-z_]+)'", sql_intraday + "\n" + sql_fill))
        self.assertTrue(helper_statuses, "Expected TS helper status literals to be present.")
        self.assertTrue(sql_statuses, "Expected SQL status literals to be present.")

        normalized_sql = {s.upper() for s in sql_statuses}
        self.assertSetEqual(
            helper_statuses,
            normalized_sql,
            "REQ-003 violation: SQL and TS status vocabularies are not canonicalized to one set.",
        )

    def test_req_004_train_phase_requires_explicit_approval(self) -> None:
        """[Req: code-derived — REQ-004] train dispatch must propagate explicit approval flag."""
        captured: dict[str, object] = {}

        def fake_train(*, dry_run: bool, approved: bool) -> dict[str, object]:
            captured["dry_run"] = dry_run
            captured["approved"] = approved
            return {"phase": "train", "approved": approved, "dry_run": dry_run}

        with patch.dict(pipeline.PHASE_MAP, {"train": fake_train}, clear=False):
            result = pipeline.run_phase(
                "train",
                dry_run=False,
                approve_training=False,
                approve_promotion=False,
            )

        self.assertEqual(result["phase"], "train")
        self.assertFalse(captured["approved"])
        self.assertFalse(captured["dry_run"])

    def test_req_004_promote_phase_requires_explicit_approval(self) -> None:
        """[Req: code-derived — REQ-004] promote dispatch must force dry_run when unapproved."""
        captured: dict[str, object] = {}

        def fake_promote(*, dry_run: bool, approved: bool) -> dict[str, object]:
            captured["dry_run"] = dry_run
            captured["approved"] = approved
            return {"phase": "promote", "approved": approved, "dry_run": dry_run}

        with patch.dict(pipeline.PHASE_MAP, {"promote": fake_promote}, clear=False):
            result = pipeline.run_phase(
                "promote",
                dry_run=False,
                approve_training=False,
                approve_promotion=False,
            )

        self.assertEqual(result["phase"], "promote")
        self.assertFalse(captured["approved"])
        self.assertTrue(captured["dry_run"])

    def test_req_005_runtime_pull_routes_include_fallback_language(self) -> None:
        """[Req: code-derived — REQ-005] AI-first routes should expose fallback/degraded behavior."""
        strategy = read_text("app/api/strategy/posture/route.ts")
        sentiment = read_text("app/api/sentiment/overview/route.ts")
        legislation = read_text("app/api/legislation/feed/route.ts")
        vegas = read_text("app/api/vegas/intel/route.ts")

        joined = "\n".join([strategy, sentiment, legislation, vegas]).lower()
        self.assertRegex(joined, r"fallback|snapshot|degraded")

    def test_req_006_readme_does_not_hardcode_localhost_3000(self) -> None:
        """[Req: code-derived — REQ-006] operator docs should avoid prohibited hardcoded-port guidance."""
        readme = read_text("README.md").lower()
        self.assertNotIn("localhost:3000", readme)

    def test_req_007_writeup_path_requirement_statement_present(self) -> None:
        reqs = read_text("quality/REQUIREMENTS.md")
        self.assertIn("Per-bug writeups are placed at quality/writeups/BUG-<id>.md.", reqs)

    def test_req_008_fix_patch_path_requirement_statement_present(self) -> None:
        reqs = read_text("quality/REQUIREMENTS.md")
        self.assertIn("Fix patches are placed at quality/patches/BUG-<id>-fix.patch.", reqs)

    def test_req_009_regression_patch_path_requirement_statement_present(self) -> None:
        reqs = read_text("quality/REQUIREMENTS.md")
        self.assertIn("Regression-test patches are placed at quality/patches/BUG-<id>-regression-test.patch.", reqs)

    def test_req_010_code_review_path_requirement_statement_present(self) -> None:
        reqs = read_text("quality/REQUIREMENTS.md")
        self.assertIn("Code review output is placed at quality/code_reviews/.", reqs)

    def test_req_011_spec_audit_path_requirement_statement_present(self) -> None:
        reqs = read_text("quality/REQUIREMENTS.md")
        self.assertIn("Spec audit outputs (auditor reports + triage) are placed at quality/spec_audits/.", reqs)

    def test_req_012_sidecar_results_path_requirement_statement_present(self) -> None:
        reqs = read_text("quality/REQUIREMENTS.md")
        self.assertIn(
            "Sidecar JSON results (tdd-results.json, integration-results.json, recheck-results.json) are placed at quality/results/.",
            reqs,
        )

    def test_req_013_mechanical_path_requirement_statement_present(self) -> None:
        reqs = read_text("quality/REQUIREMENTS.md")
        self.assertIn("Mechanical-verification artifacts (verify.sh + *_cases.txt) are placed at quality/mechanical/.", reqs)

    def test_req_014_workspace_forbidden_requirement_statement_present(self) -> None:
        reqs = read_text("quality/REQUIREMENTS.md")
        self.assertIn("quality/workspace/<name>/ is forbidden", reqs)


class FitnessScenarioTests(unittest.TestCase):
    def test_scenario_1_intraday_source_field_not_hardcoded_when_fallback_needed(self) -> None:
        """[Req: code-derived — REQ-001] fallback-capable routes should not hardcode one source label."""
        source = read_text("app/api/zl/intraday/route.ts")
        self.assertNotIn(
            'source: "mkt.price_15m"',
            source,
            "Scenario 1 risk: source label is hardcoded despite fallback contract.",
        )

    def test_scenario_2_forecast_overlay_gate_is_not_hard_disabled(self) -> None:
        """[Req: code-derived — REQ-002] chart target-zone rendering should not be globally disabled."""
        chart = read_text("components/chart/ZlCandlestickChart.tsx")
        self.assertIn("SHOW_FORECAST_TARGET_OVERLAY = true", chart)

    def test_scenario_3_probability_surface_and_dashboard_share_contract_path(self) -> None:
        """[Req: code-derived — REQ-002] equivalent consumers should not require route-specific parsers."""
        surface = read_text("components/dashboard/ProbabilitySurface.tsx")
        dashboard = read_text("app/(protected)/dashboard/page.tsx")
        self.assertIn("/api/zl/target-zones", dashboard)
        self.assertNotIn(
            "/api/zl/forecast-targets",
            surface,
            "Scenario 3 risk: probability surface still depends on divergent endpoint contract.",
        )

    def test_scenario_4_ingest_status_values_do_not_split_case_domains(self) -> None:
        """[Req: code-derived — REQ-003] case-domain drift in status values should be absent."""
        helper = read_text("lib/server/ingest-run.ts")
        self.assertNotRegex(helper, r'"SUCCESS"|"FAILED"|"RUNNING"')

    def test_scenario_5_train_models_contains_explicit_approval_guard(self) -> None:
        """[Req: code-derived — REQ-004] train_models should enforce explicit approval check."""
        train_source = read_text("python/fusion/train_models.py")
        self.assertIn("if not approved:", train_source)
        self.assertIn("Training requires explicit approval", train_source)

    def test_scenario_6_routes_document_snapshot_and_trusted_pull_order(self) -> None:
        """[Req: code-derived — REQ-005] runtime pull routes should expose snapshot/degraded semantics."""
        strategy = read_text("app/api/strategy/posture/route.ts").lower()
        self.assertRegex(strategy, r"snapshot|fallback")

    def test_scenario_7_snapshot_allowlist_is_not_empty(self) -> None:
        """[Req: code-derived — REQ-004] trusted snapshot sources list should be non-empty."""
        snapshot = read_text("lib/server/ai-snapshot.ts")
        entries = re.findall(r'"([a-z0-9\-]+)"', snapshot.split("TRUSTED_SNAPSHOT_SOURCES", 1)[1])
        self.assertGreaterEqual(len(entries), 4)

    def test_scenario_8_readme_drift_is_detectable(self) -> None:
        """[Req: code-derived — REQ-006] README should align with authority startup guidance."""
        readme = read_text("README.md")
        agents = read_text("AGENTS.md")
        self.assertNotIn("localhost:3000", readme)
        self.assertIn("No hardcoded port 3000", agents)


class BoundaryAndEdgeCaseTests(unittest.TestCase):
    def test_boundary_intraday_tables_exist_in_migration_contract(self) -> None:
        """[Req: inferred — from mkt schema tables] both intraday table levels exist."""
        migration = read_text("supabase/migrations/202603180002_mkt.sql")
        self.assertIn("create table if not exists mkt.price_15m", migration.lower())
        self.assertIn("create table if not exists mkt.price_1m", migration.lower())

    def test_boundary_horizon_allowlist_parity_across_routes(self) -> None:
        """[Req: inferred — REQ-002 parity pattern] horizon allowlist should match across forecast routes."""
        forecast = read_text("app/api/zl/forecast/route.ts")
        target = read_text("app/api/zl/target-zones/route.ts")
        targets = read_text("app/api/zl/forecast-targets/route.ts")

        pattern = re.compile(r"AG_HORIZON_DAYS\s*=\s*\[30,\s*90,\s*180\]")
        self.assertRegex(forecast, pattern)
        self.assertRegex(target, pattern)
        self.assertRegex(targets, pattern)

    def test_boundary_legacy_horizon_map_parity_across_routes(self) -> None:
        """[Req: inferred — REQ-002 parity pattern] legacy remap should match across forecast routes."""
        expected_pairs = ["7: 30", "14: 90", "30: 180"]
        for rel in [
            "app/api/zl/forecast/route.ts",
            "app/api/zl/target-zones/route.ts",
            "app/api/zl/forecast-targets/route.ts",
        ]:
            text = read_text(rel)
            for pair in expected_pairs:
                self.assertIn(pair, text)

    def test_boundary_trusted_snapshot_sources_are_exactly_expected_set(self) -> None:
        """[Req: inferred — snapshot allowlist] trusted source list should match expected identifiers."""
        source = read_text("lib/server/ai-snapshot.ts")
        values = set(
            re.findall(r'"(trusted-live-pull|trusted-authority-pull|ai-daily-refresh|chatgpt-pro-subscription-refresh)"', source)
        )
        self.assertSetEqual(
            values,
            {
                "trusted-live-pull",
                "trusted-authority-pull",
                "ai-daily-refresh",
                "chatgpt-pro-subscription-refresh",
            },
        )

    def test_boundary_overlay_attach_and_detach_paths_match_gate(self) -> None:
        """[Req: inferred — chart overlay lifecycle] attach/detach should both be gated consistently."""
        chart = read_text("components/chart/ZlCandlestickChart.tsx")
        attach_gated = "if (SHOW_FORECAST_TARGET_OVERLAY) {\n      series.attachPrimitive(forecastTargetsPrimitive);" in chart
        detach_gated = "if (SHOW_FORECAST_TARGET_OVERLAY) {\n          series.detachPrimitive(forecastTargetsPrimitive);" in chart
        self.assertTrue(attach_gated)
        self.assertTrue(detach_gated)

    def test_boundary_pipeline_dispatch_train_passes_approved_flag(self) -> None:
        """[Req: inferred — run_phase dispatch] train dispatch passes approval argument through."""
        captured: dict[str, object] = {}

        def fake_train(*, dry_run: bool, approved: bool) -> dict[str, object]:
            captured["dry_run"] = dry_run
            captured["approved"] = approved
            return {"ok": True}

        with patch.dict(pipeline.PHASE_MAP, {"train": fake_train}, clear=False):
            pipeline.run_phase(
                "train",
                dry_run=True,
                approve_training=True,
                approve_promotion=False,
            )

        self.assertTrue(captured["dry_run"])
        self.assertTrue(captured["approved"])


if __name__ == "__main__":
    unittest.main()
