#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-05-16 · Project: ZINC-FUSION-V16

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MECH="$ROOT/quality/mechanical"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

check_snapshot() {
  local generated="$1"
  local baseline="$2"
  if diff -u "$baseline" "$generated" >/dev/null; then
    echo "PASS  $(basename "$baseline")"
  else
    echo "FAIL  $(basename "$baseline")"
    diff -u "$baseline" "$generated"
    return 1
  fi
}

# 1) Trusted snapshot source whitelist
awk '/TRUSTED_SNAPSHOT_SOURCES/{capture=1} capture{print} /\]\);/{if(capture){capture=0; exit}}' "$ROOT/lib/server/ai-snapshot.ts" \
  | rg -o '"[^"]+"' \
  | tr -d '"' \
  > "$TMP/trusted_snapshot_sources.txt"
check_snapshot "$TMP/trusted_snapshot_sources.txt" "$MECH/trusted_snapshot_sources.txt"

# 2) Horizon normalization blocks across route family
rg -n 'const AG_HORIZON_DAYS|const LEGACY_HORIZON_MAP|function normalizeHorizon|if \(modelVersion === "legacy"\)|return AG_HORIZON_DAYS.has' "$ROOT/app/api/zl/forecast/route.ts" \
  > "$TMP/forecast_normalize_horizon.txt"
check_snapshot "$TMP/forecast_normalize_horizon.txt" "$MECH/forecast_normalize_horizon.txt"

rg -n 'const AG_HORIZON_DAYS|const LEGACY_HORIZON_MAP|function normalizeHorizon|if \(modelVersion === "legacy"\)|return AG_HORIZON_DAYS.has' "$ROOT/app/api/zl/target-zones/route.ts" \
  > "$TMP/target_zones_normalize_horizon.txt"
check_snapshot "$TMP/target_zones_normalize_horizon.txt" "$MECH/target_zones_normalize_horizon.txt"

rg -n 'const AG_HORIZON_DAYS|const LEGACY_HORIZON_MAP|function normalizeHorizon|if \(modelVersion === "legacy"\)|return AG_HORIZON_DAYS.has' "$ROOT/app/api/zl/forecast-targets/route.ts" \
  > "$TMP/forecast_targets_normalize_horizon.txt"
check_snapshot "$TMP/forecast_targets_normalize_horizon.txt" "$MECH/forecast_targets_normalize_horizon.txt"

# 3) Envelope warning semantics across contract and gate
rg -n 'ApiEnvelope|ApiErrorEnvelope|warning' "$ROOT/lib/contracts/api.ts" \
  > "$TMP/api_contract_warning_fields.txt"
check_snapshot "$TMP/api_contract_warning_fields.txt" "$MECH/api_contract_warning_fields.txt"

rg -n 'warning|jq|gate6' "$ROOT/scripts/verify/gate6.sh" \
  > "$TMP/gate6_warning_checks.txt"
check_snapshot "$TMP/gate6_warning_checks.txt" "$MECH/gate6_warning_checks.txt"

echo "Mechanical verification complete"
